os:
  open: nvim {{filename}}
git:
  paging:
    # externalDiffCommand: difft --color=always --display=inline --syntax-highlight=off # this seems to be bugged and not show the diff correctly. The plus is it uses structured diff
    colorArg: always
    pager: delta --dark --paging=never
  disableForcePushing: true
  # gui:

# Use the mocha catppuccin theme
# theme:
#   activeBorderColor:
#     - '#89b4fa'
#     - bold
#   inactiveBorderColor:
#     - '#a6adc8'
#   optionsTextColor:
#     - '#89b4fa'
#   selectedLineBgColor:
#     - '#313244'
#   selectedRangeBgColor:
#     - '#313244'
#   cherryPickedCommitBgColor:
#     - '#45475a'
#   cherryPickedCommitFgColor:
#     - '#89b4fa'
#   unstagedChangesColor:
#     - '#f38ba8'
#   defaultFgColor:
#     - '#cdd6f4'
#   searchingActiveBorderColor:
#     - '#f9e2af'
